name: Build RCCar & ControlTower

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_rccar:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies for RCCar
      run: sudo apt update && sudo apt install -y git build-essential cmake libqt5serialport5-dev libgpiod-dev

    - name: Install MAVSDK
      run: wget https://github.com/mavlink/MAVSDK/releases/download/v2.0.1/libmavsdk-dev_2.0.1_ubuntu22.04_amd64.deb && sudo dpkg --install libmavsdk-dev_2.0.1_ubuntu22.04_amd64.deb

    - name: RCCar - Checkout
      uses: actions/checkout@v4
      with:
        repository: RISE-Dependable-Transport-Systems/RCCar
        path: RCCar

    - name: RCCar - Checkout WayWise
      uses: actions/checkout@v4
      with:
        path: RCCar/WayWise

    - name: RCCar - configure CMake
      run: cmake -S ${{github.workspace}}/RCCar -B ${{github.workspace}}/RCCar/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: RCCar - build
      run: cmake --build ${{github.workspace}}/RCCar/build --config ${{env.BUILD_TYPE}}

  build_controltower:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies for ControlTower
      run: sudo apt update && sudo apt install -y git build-essential cmake qtcreator qtbase5-dev libqt5serialport5-dev qtmultimedia5-dev libqt5gamepad5-dev

    - name: Install MAVSDK
      run: wget https://github.com/mavlink/MAVSDK/releases/download/v2.0.1/libmavsdk-dev_2.0.1_ubuntu22.04_amd64.deb && sudo dpkg --install libmavsdk-dev_2.0.1_ubuntu22.04_amd64.deb

    - name: ControlTower - Checkout
      uses: actions/checkout@v4
      with:
        repository: RISE-Dependable-Transport-Systems/ControlTower
        path: ControlTower

    - name: ControlTower - Checkout WayWise
      uses: actions/checkout@v4
      with:
        path: ControlTower/WayWise

    - name: ControlTower - configure CMake
      run: cmake -S ${{github.workspace}}/ControlTower -B ${{github.workspace}}/ControlTower/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: ControlTower - build
      run: cmake --build ${{github.workspace}}/ControlTower/build --config ${{env.BUILD_TYPE}}

