name: Build RCCar and ControlTower using CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install apt dependencies
      run: sudo apt update && sudo apt install -y git build-essential cmake libqt5serialport5-dev libgpiod-dev

    - name: Install MAVSDK
      run: wget https://github.com/mavlink/MAVSDK/releases/download/v2.0.1/libmavsdk-dev_2.0.1_ubuntu22.04_amd64.deb && sudo dpkg --install libmavsdk-dev_2.0.1_ubuntu22.04_amd64.deb

    - name: RCCar - Checkout
      uses: actions/checkout@v4
      with:
        repository: RISE-Dependable-Transport-Systems/RCCar
        path: RCCar

    - name: RCCar - Checkout WayWise
      uses: actions/checkout@v4
      with:
        path: RCCar/WayWise

    - name: RCCar - configure CMake
      run: cmake -S ${{github.workspace}}/RCCar -B ${{github.workspace}}/RCCar/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: RCCar - build
      run: cmake --build ${{github.workspace}}/RCCar/build --config ${{env.BUILD_TYPE}}

    - name: ControlTower - Checkout
      uses: actions/checkout@v4
      with:
        repository: RISE-Dependable-Transport-Systems/ControlTower
        path: ControlTower

    - name: ControlTower - Checkout WayWise
      uses: actions/checkout@v4
      with:
        path: ControlTower/WayWise

    - name: ControlTower - configure CMake
      run: cmake -S ${{github.workspace}}/ControlTower -B ${{github.workspace}}/ControlTower/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: ControlTower - build
      run: cmake --build ${{github.workspace}}/ControlTower/build --config ${{env.BUILD_TYPE}}

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      # Execute tests defined by the CMake configuration.
#      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#      run: ctest -C ${{env.BUILD_TYPE}}

